// user
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

// jobs
export const RECEIVE_JOBS = "RECEIVE_JOBS";
export const FETCH_JOBS = "FETCH_JOBS";

// degree types filter
export const DEGREES = "DEGREES";
export const SET_SELECTED_DEGREES = "SET_SELECTED_DEGREES";
export const INCLUDE_JOB_BY_DEGREE = "INCLUDE_JOB_BY_DEGREE";
export const RECEIVE_DEGREES = "RECEIVE_DEGREES";
export const FETCH_DEGREES = "FETCH_DEGREES";

// organizations filter
export const ORGANIZATIONS = "ORGANIZATIONS";
export const SET_SELECTED_ORGANIZATIONS = "SET_SELECTED_ORGANIZATIONS";
export const INCLUDE_JOB_BY_ORGANIZATION = "INCLUDE_JOB_BY_ORGANIZATION";

// job types filter
export const JOB_TYPES = "JOB_TYPES";
export const SET_SELECTED_JOB_TYPES = "SET_SELECTED_JOB_TYPES";
export const INCLUDE_JOB_BY_JOB_TYPE = "INCLUDE_JOB_BY_JOB_TYPE";

export const FILTERED_JOBS = "FILTERED_JOBS";
export const CLEAR_JOB_FILTERS = "CLEAR_JOB_FILTERS";

export const SET_SKILLS_SEARCH_TERM = "SET_SKILLS_SEARCH_TERM";
export const INCLUDE_JOB_BY_SKILL = "INCLUDE_JOB_BY_SKILL";
